name: BEASTfrmEAST
favicon: null
layout_spectrum: 0.38935753516852856
typography_spectrum: 0.032452576560899615
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.0036694519221782684
  lightness: 0.03677344066090882
  saturation: 0.7553775892592967
  rhythmicContrast: 0.35093502211384475
purpose: []
